// Structured error codes for programmatic error handling across Sygil.
export const SygilErrorCode = {
  // Gate errors
  GATE_TIMEOUT: "GATE_TIMEOUT",
  GATE_SCRIPT_FAILED: "GATE_SCRIPT_FAILED",
  GATE_CONDITION_FAILED: "GATE_CONDITION_FAILED",
  GATE_PATH_TRAVERSAL: "GATE_PATH_TRAVERSAL",

  // Node errors
  NODE_TIMEOUT: "NODE_TIMEOUT",
  NODE_IDLE_TIMEOUT: "NODE_IDLE_TIMEOUT",
  NODE_STALLED: "NODE_STALLED",
  NODE_CRASHED: "NODE_CRASHED",
  NODE_CONTRACT_FAILED: "NODE_CONTRACT_FAILED",

  // Human review errors
  HUMAN_REVIEW_TIMEOUT: "HUMAN_REVIEW_TIMEOUT",

  // Worktree errors
  WORKTREE_MERGE_CONFLICT: "WORKTREE_MERGE_CONFLICT",

  // Adapter errors
  ADAPTER_UNAVAILABLE: "ADAPTER_UNAVAILABLE",
  ADAPTER_SPAWN_FAILED: "ADAPTER_SPAWN_FAILED",
  ADAPTER_RATE_LIMITED: "ADAPTER_RATE_LIMITED",

  // Workflow errors
  WORKFLOW_CANCELLED: "WORKFLOW_CANCELLED",
  WORKFLOW_VALIDATION_FAILED: "WORKFLOW_VALIDATION_FAILED",
  WORKFLOW_NODE_FAILED: "WORKFLOW_NODE_FAILED",
  WORKFLOW_PAUSE_FAILED: "WORKFLOW_PAUSE_FAILED",
  WORKFLOW_RESUME_FAILED: "WORKFLOW_RESUME_FAILED",

  // Checkpoint errors
  CHECKPOINT_WRITE_FAILED: "CHECKPOINT_WRITE_FAILED",
  CHECKPOINT_LOAD_FAILED: "CHECKPOINT_LOAD_FAILED",
} as const;

export type SygilErrorCode = (typeof SygilErrorCode)[keyof typeof SygilErrorCode];

export interface SygilError {
  code: SygilErrorCode;
  message: string;
  nodeId?: string;
  edgeId?: string;
  details?: Record<string, unknown>;
}
